version: '3.7'
services:
  spring_boot_app:
    container_name: telegram-bot
    image: eclipse-temurin:21-alpine
  # need to insert your own secrets and addresses
    environment:
      google.clientId: 149242102535-5uo3kngi681dsqp97d6kocntg8esh0ib.apps.googleusercontent.com
      server.ssl.key-alias: ec2-16-171-168-150.eu-north-1.compute.amazonaws.com
      server.ssl.key-store-password: gor2set
      telegram.webhook-path: https://ec2-16-171-168-150.eu-north-1.compute.amazonaws.com
      google.redirectionUri: https://ec2-16-171-168-150.eu-north-1.compute.amazonaws.com:8443/googleapiresponse/code
    volumes:
      - /home/ubuntu:/app
    ports:
      - "8443:8443"
    depends_on:
      - my-postgres-container
    command: >
      sh -c "while ! nc -z my-postgres-container 5432; do sleep 1; done;
             java -jar /app/WatchLaterYoutubeBot-0.0.1-SNAPSHOT.jar"

  my-postgres-container:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: