version: '3'

services:
  app:
    image: 'spring-app:latest'
    build:
      context: ../../
      dockerfile: infrastructure/docker/spring_app.Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=$db_username
      - SPRING_DATASOURCE_PASSWORD=$db_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "80:80"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=$db_username
      - POSTGRES_PASSWORD=$db_password
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
